import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

public class Aplicacio extends javax.swing.JFrame {
    ArrayList list = new ArrayList();
    CPersona persona;
    CCompteBancari compte;
    Iterator ite;
    int comp;
    /**
     * Creates new form Aplicacio
     */
    public Aplicacio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearCompte = new javax.swing.JButton();
        modificarCompte = new javax.swing.JButton();
        eliminarCompte = new javax.swing.JButton();
        ingressar = new javax.swing.JButton();
        extreureDiners = new javax.swing.JButton();
        modificarNum = new javax.swing.JButton();
        sortir = new javax.swing.JButton();
        consultarSaldo = new javax.swing.JButton();
        ingressarDiners = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crearCompte.setText("Crear Compte");
        crearCompte.setMaximumSize(new java.awt.Dimension(155, 25));
        crearCompte.setMinimumSize(new java.awt.Dimension(155, 25));
        crearCompte.setPreferredSize(new java.awt.Dimension(155, 25));
        crearCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCompteActionPerformed(evt);
            }
        });

        modificarCompte.setText("Modificar Compte");
        modificarCompte.setMaximumSize(new java.awt.Dimension(155, 25));
        modificarCompte.setMinimumSize(new java.awt.Dimension(155, 25));
        modificarCompte.setPreferredSize(new java.awt.Dimension(155, 25));
        modificarCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarCompteActionPerformed(evt);
            }
        });

        eliminarCompte.setText("Eliminar Compte");
        eliminarCompte.setMaximumSize(new java.awt.Dimension(155, 25));
        eliminarCompte.setMinimumSize(new java.awt.Dimension(155, 25));
        eliminarCompte.setPreferredSize(new java.awt.Dimension(155, 25));
        eliminarCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCompteActionPerformed(evt);
            }
        });

        ingressar.setText("Ingressar Diners");
        ingressar.setMaximumSize(new java.awt.Dimension(155, 25));
        ingressar.setMinimumSize(new java.awt.Dimension(155, 25));
        ingressar.setPreferredSize(new java.awt.Dimension(155, 25));
        ingressar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingressarActionPerformed(evt);
            }
        });

        extreureDiners.setText("Extreure Diners");
        extreureDiners.setMaximumSize(new java.awt.Dimension(155, 25));
        extreureDiners.setMinimumSize(new java.awt.Dimension(155, 25));
        extreureDiners.setPreferredSize(new java.awt.Dimension(155, 25));
        extreureDiners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extreureDinersActionPerformed(evt);
            }
        });

        modificarNum.setText("Modificar Num Secret");
        modificarNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarNumActionPerformed(evt);
            }
        });

        sortir.setText("Sortir");
        sortir.setMaximumSize(new java.awt.Dimension(155, 25));
        sortir.setMinimumSize(new java.awt.Dimension(155, 25));
        sortir.setPreferredSize(new java.awt.Dimension(155, 25));
        sortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortirActionPerformed(evt);
            }
        });

        consultarSaldo.setText("Consultar Saldo");
        consultarSaldo.setMaximumSize(new java.awt.Dimension(155, 25));
        consultarSaldo.setMinimumSize(new java.awt.Dimension(155, 25));
        consultarSaldo.setPreferredSize(new java.awt.Dimension(155, 25));
        consultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarSaldoActionPerformed(evt);
            }
        });

        ingressarDiners.setText("Ingressar a un altre compte");
        ingressarDiners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingressarDinersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modificarNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sortir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ingressar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarCompte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modificarCompte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crearCompte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(extreureDiners, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ingressarDiners, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crearCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(ingressar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(extreureDiners, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingressarDiners)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCompteActionPerformed
        new CCrearCompte(this).setVisible(true);
    }//GEN-LAST:event_crearCompteActionPerformed

    private void modificarCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarCompteActionPerformed
        new CModificarCompte(this).setVisible(true);
    }//GEN-LAST:event_modificarCompteActionPerformed

    private void eliminarCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCompteActionPerformed
        new CEliminarCompte(this).setVisible(true);
    }//GEN-LAST:event_eliminarCompteActionPerformed

    private void ingressarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingressarActionPerformed
        new CIngressar(this).setVisible(true);
    }//GEN-LAST:event_ingressarActionPerformed

    private void consultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarSaldoActionPerformed
       new CConsultarSaldo(this).setVisible(true);
    }//GEN-LAST:event_consultarSaldoActionPerformed

    private void extreureDinersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extreureDinersActionPerformed
        new CExtreure(this).setVisible(true);
    }//GEN-LAST:event_extreureDinersActionPerformed

    private void modificarNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarNumActionPerformed
        new CModificarNumero(this).setVisible(true);
    }//GEN-LAST:event_modificarNumActionPerformed

    private void sortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sortirActionPerformed

    private void ingressarDinersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingressarDinersActionPerformed
        new CConsultarSaldo(this).setVisible(true);
    }//GEN-LAST:event_ingressarDinersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarSaldo;
    private javax.swing.JButton crearCompte;
    private javax.swing.JButton eliminarCompte;
    private javax.swing.JButton extreureDiners;
    private javax.swing.JButton ingressar;
    private javax.swing.JButton ingressarDiners;
    private javax.swing.JButton modificarCompte;
    private javax.swing.JButton modificarNum;
    private javax.swing.JButton sortir;
    // End of variables declaration//GEN-END:variables
}
